from app.models.alumno import Alumno
from app.models.usuario import Usuario
from app.models.sucursal import Sucursal
from app.models.pago import Pago
from app.models.asistencia import Asistencia
from app.models.historial import HistorialCambio
from app.models.catalogo import ProgramaCatalogo
from app.models.bitacora import Bitacora
from app.models.reporte import ReporteMensual
from app.models.aviso import Aviso
from app.models.confirmacion_asistencia import ConfirmacionAsistencia
from app.models.recuperacion import ClaseRecuperacion
from app.models.prospecto_calendario import ProspectoCalendario
from app.models.actividad_docente import ActividadDocente
from app.models.informe import Informe
from app.models.resumen_semanal import ResumenSemanal